# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from typing import Union
from .. import utilities, tables

__config__ = pulumi.Config('influxdb')

password = __config__.get('password') or utilities.get_env('INFLUXDB_PASSWORD')

skip_ssl_verify = __config__.get('skipSslVerify') or utilities.get_env_bool('INFLUXDB_SKIP_SSL_VERIFY')

url = __config__.get('url') or utilities.get_env('INFLUXDB_URL')

username = __config__.get('username') or utilities.get_env('INFLUXDB_USERNAME')

