# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from typing import Union
from . import utilities, tables

class Database(pulumi.CustomResource):
    name: pulumi.Output[str]
    """
    The name of the retention policy
    """
    retention_policies: pulumi.Output[list]
    """
    A list of retention policies for specified database
    
      * `default` (`bool`) - Marks current retention policy as default. Default value is false.
      * `duration` (`str`) - The duration for retention policy, format of duration can be found at InfluxDB Documentation.
      * `name` (`str`) - The name of the retention policy
      * `replication` (`float`) - Determines how many copies of data points are stored in a cluster. Not applicable for single node / Open Source version of InfluxDB. Default value of 1.
      * `shardgroupduration` (`str`) - Determines how much time each shard group spans. How and why to modify can be found at InfluxDB Documentation.
    """
    def __init__(__self__, resource_name, opts=None, name=None, retention_policies=None, __props__=None, __name__=None, __opts__=None):
        """
        The database resource allows a database to be created on an InfluxDB server.
        
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] name: The name of the retention policy
        :param pulumi.Input[list] retention_policies: A list of retention policies for specified database
        
        The **retention_policies** object supports the following:
        
          * `default` (`pulumi.Input[bool]`) - Marks current retention policy as default. Default value is false.
          * `duration` (`pulumi.Input[str]`) - The duration for retention policy, format of duration can be found at InfluxDB Documentation.
          * `name` (`pulumi.Input[str]`) - The name of the retention policy
          * `replication` (`pulumi.Input[float]`) - Determines how many copies of data points are stored in a cluster. Not applicable for single node / Open Source version of InfluxDB. Default value of 1.
          * `shardgroupduration` (`pulumi.Input[str]`) - Determines how much time each shard group spans. How and why to modify can be found at InfluxDB Documentation.

        > This content is derived from https://github.com/terraform-providers/terraform-provider-influxdb/blob/master/website/docs/r/database.html.markdown.
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = dict()

            __props__['name'] = name
            __props__['retention_policies'] = retention_policies
        super(Database, __self__).__init__(
            'influxdb:index/database:Database',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name, id, opts=None, name=None, retention_policies=None):
        """
        Get an existing Database resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.
        
        :param str resource_name: The unique name of the resulting resource.
        :param str id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] name: The name of the retention policy
        :param pulumi.Input[list] retention_policies: A list of retention policies for specified database
        
        The **retention_policies** object supports the following:
        
          * `default` (`pulumi.Input[bool]`) - Marks current retention policy as default. Default value is false.
          * `duration` (`pulumi.Input[str]`) - The duration for retention policy, format of duration can be found at InfluxDB Documentation.
          * `name` (`pulumi.Input[str]`) - The name of the retention policy
          * `replication` (`pulumi.Input[float]`) - Determines how many copies of data points are stored in a cluster. Not applicable for single node / Open Source version of InfluxDB. Default value of 1.
          * `shardgroupduration` (`pulumi.Input[str]`) - Determines how much time each shard group spans. How and why to modify can be found at InfluxDB Documentation.

        > This content is derived from https://github.com/terraform-providers/terraform-provider-influxdb/blob/master/website/docs/r/database.html.markdown.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = dict()
        __props__["name"] = name
        __props__["retention_policies"] = retention_policies
        return Database(resource_name, opts=opts, __props__=__props__)
    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

