# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

_SNAKE_TO_CAMEL_CASE_TABLE = {
    "retention_policies": "retentionPolicies",
    "skip_ssl_verify": "skipSslVerify",
}

_CAMEL_TO_SNAKE_CASE_TABLE = {
    "retentionPolicies": "retention_policies",
    "skipSslVerify": "skip_ssl_verify",
}
