// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("influxdb");

export let password: string | undefined = __config.get("password") || utilities.getEnv("INFLUXDB_PASSWORD");
export let skipSslVerify: boolean | undefined = __config.getObject<boolean>("skipSslVerify") || utilities.getEnvBoolean("INFLUXDB_SKIP_SSL_VERIFY");
export let url: string | undefined = __config.get("url") || utilities.getEnv("INFLUXDB_URL");
export let username: string | undefined = __config.get("username") || utilities.getEnv("INFLUXDB_USERNAME");
