// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
	"github.com/pulumi/pulumi/sdk/go/pulumi/config"
)

func GetPassword(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "influxdb:password")
	if err == nil {
		return v
	}
	if dv, ok := getEnvOrDefault("", nil, "INFLUXDB_PASSWORD").(string); ok {
		return dv
	}
	return v
}

func GetSkipSslVerify(ctx *pulumi.Context) bool {
	v, err := config.TryBool(ctx, "influxdb:skipSslVerify")
	if err == nil {
		return v
	}
	if dv, ok := getEnvOrDefault(false, parseEnvBool, "INFLUXDB_SKIP_SSL_VERIFY").(bool); ok {
		return dv
	}
	return v
}

func GetUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "influxdb:url")
	if err == nil {
		return v
	}
	if dv, ok := getEnvOrDefault("", nil, "INFLUXDB_URL").(string); ok {
		return dv
	}
	return v
}

func GetUsername(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "influxdb:username")
	if err == nil {
		return v
	}
	if dv, ok := getEnvOrDefault("", nil, "INFLUXDB_USERNAME").(string); ok {
		return dv
	}
	return v
}
