// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";

export interface DatabaseRetentionPolicy {
    default?: pulumi.Input<boolean>;
    duration: pulumi.Input<string>;
    name: pulumi.Input<string>;
    replication?: pulumi.Input<number>;
    shardgroupduration?: pulumi.Input<string>;
}

export interface UserGrant {
    database: pulumi.Input<string>;
    privilege: pulumi.Input<string>;
}
