// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as outputs from "../types/output";

export interface DatabaseRetentionPolicy {
    default?: boolean;
    duration: string;
    name: string;
    replication?: number;
    shardgroupduration?: string;
}

export interface UserGrant {
    database: string;
    privilege: string;
}
